import SideDrawer, {SideDrawerSmall} from "@/components/SideDrawer";
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";
import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default async function RootLayout({children}: { children: React.ReactNode}) {
    // const { getUser } = getKindeServerSession()
    // const user = await getUser()
  
    // const ADMIN_EMAIL = process.env.ADMIN_EMAIL
  
    // if (!user || user.email !== ADMIN_EMAIL) {
    //   return notFound()
    // }

  return (
    <div className="flex">
        <div className="w-60 lmd:w-20 xsm:hidden fixed h-[100vh]">
            <SideDrawer />
        </div>
        <div className="relative min-h-[100vh] w-[calc(100%-15rem)] left-60 lmd:left-20 lmd:w-[calc(100%-5rem)] xsm:left-0 xsm:w-full">
            <SideDrawerSmall/>
            {children}
        </div>
    </div>
  );
}
